name: Celes static analysis
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "--check --verbose"

  codacy-analysis-cli:
      name: Codacy Analysis CLI
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@main

        - name: Run Codacy Analysis CLI
          uses: codacy/codacy-analysis-cli-action@master
